config/routes.rb
# -*- encoding : utf-8 -*-
UrboretumServer::Application.routes.draw do

  resources :users, :only => [:index, :show] do
    member do
      get :album
      get :map
    end
  end

  resources :towns do
    collection do
      get :map
      get :guess
    end
    member do
      get :guess
      post :mark
    end
  end

  resources :visits, :only => :show

  root :to => 'towns#map'

  get "/info" => "public#info", :as => :info

  get "/oauth/connect" => 'instagram#connect', :as => :connect
  get "/oauth/callback" => 'instagram#callback'
  get "/oauth/logout" => 'instagram#logout', :as => :logout

  get "/fetch" => 'instagram#fetch', :as => :fetch
  get "/resolve" => 'instagram#resolve', :as => :resolve
  post "/resolve" => 'instagram#resolve', :as => :resolve

end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User

  attr_reader :username

  def self.all
    Visit.users.map{|x| User.new(x)}
  end

  def to_param
    @username
  end

  def visits
    Visit.by(@username)
  end

  def true_visits
    Visit.by(@username).where('media_id IS NOT NULL')
  end

  def n_visited
    visits.count
  end

  def n_true_visited
    true_visits.count
  end

  def initialize(username)
    if username.respond_to? :username
      @username = username.username
    else
      @username = username
    end
  end

end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController

  def show
    @user = User.new(params[:id])
  end

  def album
    @user = User.new(params[:id])
  end

  def map
    @user = User.new(params[:id])
    render :layout => 'map'
  end

end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
end

app/views/users/album.html.haml
%h1 Album cestovatele #{@user.username}

- unless @user.true_visits.any?
  %p Cestovatel #{@user.username} zatím nemá žádné fotografie.
- else
  %div(style="overflow:auto;")
    - @user.true_visits.each do |v|
      %div(style="float:left")
        %div(style="width:150px;height:150px")
          %div{:id => "inner_#{v.id}", :style => "display:none"}
            = link_to image_tag(v.image_url, :size => '150x150', :alt => v.town.name,  :onload => "$('#inner_#{v.id}').fadeIn(100)"), v.image_url, :rel => 'group', :title => v.town.name, :data => {:colorbox_static  => true}
    %p

app/views/users/index.html.haml
%h1 Seznam cestovatelů

%table.nice
  %thead
    %tr
      %th Uživatel
      %th Počet navštívených měst
      %th
  %tbody
    - User.all.each do |u|
      %tr
        %td= u.username
        %td
          = u.n_true_visited
          = surround '(', ')' do
            = u.n_visited
        %td
          = link_to "[seznam]", user_path(u)
          = link_to "[mapa]", map_user_path(u)
          = link_to "[album]", album_user_path(u)

app/views/users/map.html.haml
= render :partial => 'towns/towns_js', :locals => {:username => @user.username}

%div#box_menu
  %ul
    %li(style="font-weight:bold")= link_to "URBORETUM", info_path, :style => "color:#f00"
    %li mapa uživatele #{@user.username}

app/views/users/show.html.haml
%h1 Cestovatel #{@user.username}

:javascript
  window.open_department = 0;
  window.open_visit = 0;
  function openVisit(visit_id, department_i) {
    if ((window.open_department > 0) && (department_i != window.open_department)) {
      $("#district_" + window.open_department).hide();
    }
    if (window.open_visit != visit_id) {
      window.open_department = department_i;
      window.open_visit = visit_id;
      $("#district_" + window.open_department).show();
      $("#district_" + window.open_department).html('#{image_tag 'loading.gif'}');
      $.get("/visits/" + visit_id + "?target=district_" + department_i);
    } else {
      $("#district_" + window.open_department).hide();
      window.open_department = 0;
      window.open_visit = 0;
    }
  }

- Town.departments.each_with_index do |d, di|
  - towns = Town.in(d)
  - visits = @user.visits.joins(:town).where('towns.id' => towns.map(&:id))
  - if visits.any?
    %h2 Okres #{d}
    %p= (visits.map{|v| link_to_function(v.media_id ? v.town.name : "(#{v.town.name})", "openVisit(#{v.id}, #{di})")} * ", ").html_safe
    %div{:id => "district_#{di}", :style => "display:none;padding:4px;border:1px solid black;width:400px;margin-bottom:10px;margin-top:10px"}