config/routes.rb
# -*- encoding : utf-8 -*-
UrboretumServer::Application.routes.draw do

  resources :users, :only => [:index, :show] do
    member do
      get :album
      get :map
    end
  end

  resources :towns do
    collection do
      get :map
      get :guess
    end
    member do
      get :guess
      post :mark
    end
  end

  resources :visits, :only => :show

  root :to => 'towns#map'

  get "/info" => "public#info", :as => :info

  get "/oauth/connect" => 'instagram#connect', :as => :connect
  get "/oauth/callback" => 'instagram#callback'
  get "/oauth/logout" => 'instagram#logout', :as => :logout

  get "/fetch" => 'instagram#fetch', :as => :fetch
  get "/resolve" => 'instagram#resolve', :as => :resolve
  post "/resolve" => 'instagram#resolve', :as => :resolve

end

app/controllers/instagram_controller.rb
# -*- encoding : utf-8 -*-
class InstagramController < ApplicationController

  layout 'application'

  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => CALLBACK_URL)
  end

  def callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => CALLBACK_URL)
    session[:access_token] = response.access_token
    redirect_to :root
  end

  def logout
    session.delete :access_token
    redirect_to :root
  end

  def resolve
    if instagram_user
      @log = []
      params[:town_id].each do |media_id, town_id|
        image_url = params[:image_url][media_id]
        thumbnail_url = params[:thumbnail_url][media_id]
        timestamp = Time.zone.parse(params[:timestamp][media_id])

        media_id = media_id
        town_id = town_id.to_i
        town = Town.find(town_id)

        constraints = {
          :username => @instagram_user.username,
          :media_id => media_id,
          :town_id => town.id,
        }
        visit = Visit.where(constraints).first
        @log <<
          [
            visit ? "" : "(+)",
            town.name,
            timestamp.strftime("%d. %m. %Y"),
          ]
        visit ||= Visit.create(constraints)
        visit.update_attributes(
          :image_url => image_url,
          :thumbnail_url => thumbnail_url,
          :timestamp => timestamp
        )
      end
    else
      render :text => 'boo'
    end
  end

  def fetch
    if instagram_user
      @log = []
      @to_be_resolved = []
      @instagram_client.user_recent_media(:count => 9999).each do |entry|
        if entry[:tags].include?('urboretum')
          media = @instagram_client.media_item(entry.id)
          caption = media.caption.text
          town = nil
          if media.location
            latitude, longitude = media.location.latitude, media.location.longitude
            town = Town.locate(latitude, longitude)
          end
          visit = Visit.where(:media_id => entry.id).first
          if town
            constraints = {
              :username => instagram_user.username,
              :media_id => entry.id,
              :town_id => town.id,
            }
            visit = Visit.where(constraints).first || Visit.create(constraints)
            @log <<
              [
                visit ? "" : "(+)",
                media.caption.text + " => " + town.name,
                media.location.latitude.inspect + ", " + media.location.longitude.inspect,
                Time.at(entry.created_time.to_i).strftime("%d. %m. %Y"),
              ]
            constraints = {
              :username => @instagram_user.username,
              :media_id => entry.id,
              :town_id => town.id,
            }
            visit ||= Visit.create(constraints)
            visit.update_attributes(
              :image_url => media.images.standard_resolution.url,
              :thumbnail_url => media.images.thumbnail.url,
              :timestamp => Time.at(entry.created_time.to_i)
            )
          else
            unless visit
              @to_be_resolved << [caption, entry.id, media.images.standard_resolution.url, media.images.thumbnail.url, Time.at(entry.created_time.to_i)]
            else
              @log << ["", visit.town.name, "", "(-)", visit.timestamp.strftime("%.d. %m. %Y")]
            end
          end
        end
      end

      puts @to_be_resolved.inspect
    else
      render :text => 'boo'
    end
  end

end

app/helpers/instagram_helper.rb
# -*- encoding : utf-8 -*-
module InstagramHelper
end

app/views/instagram/fetch.html.haml
%h1 Instagram [@#{instagram_user.username}]

%table
  - @log.each do |line|
    %tr
      = (line.map{|s| "<td>#{s}</td>".html_safe} * "\n".html_safe).html_safe

- unless @to_be_resolved.blank?
  = form_tag resolve_path do
    %table
      - @to_be_resolved.each do |caption, media_id, image_url, thumbnail_url, timestamp|
        %tr
          %td= caption
          %td= media_id
          %td= select_tag "town_id[#{media_id}]", options_from_collection_for_select(Town.all, :id, :name)
          = hidden_field_tag "image_url[#{media_id}]", image_url
          = hidden_field_tag "thumbnail_url[#{media_id}]", thumbnail_url
          = hidden_field_tag "timestamp[#{media_id}]", timestamp
    = submit_tag "Uložit"

%p= link_to 'Zpět na mapu', :root

app/views/instagram/fetch.iphone.haml
%h1 Instagram [@#{instagram_user.username}]

%table
  - @log.each do |line|
    %tr
      = (line.map{|s| "<td>#{s}</td>".html_safe} * "\n".html_safe).html_safe

- unless @to_be_resolved.blank?
  = form_tag resolve_path do
    %table
      - @to_be_resolved.each do |caption, media_id, image_url, thumbnail_url, timestamp|
        %tr
          %td= caption
          %td= media_id
          %td= select_tag "town_id[#{media_id}]", options_from_collection_for_select(Town.all, :id, :name)
          = hidden_field_tag "image_url[#{media_id}]", image_url
          = hidden_field_tag "thumbnail_url[#{media_id}]", thumbnail_url
          = hidden_field_tag "timestamp[#{media_id}]", timestamp
    = submit_tag "Uložit"

%p= link_to 'Zpět na mapu', :root

app/views/instagram/resolve.html.haml
%h1 Instagram [@#{instagram_user.username}] (bez geotagu)

%table
  - @log.each do |line|
    %tr
      = (line.map{|s| "<td>#{s}</td>".html_safe} * "\n".html_safe).html_safe

%p= link_to 'Zpět na mapu', :root

app/views/instagram/resolve.iphone.haml
%h1 Instagram [@#{instagram_user.username}] (bez geotagu)

%table
  - @log.each do |line|
    %tr
      = (line.map{|s| "<td>#{s}</td>".html_safe} * "\n".html_safe).html_safe

%p= link_to 'Zpět na mapu', :root