config/routes.rb
# -*- encoding : utf-8 -*-
UrboretumServer::Application.routes.draw do

  resources :users, :only => [:index, :show] do
    member do
      get :album
      get :map
    end
  end

  resources :towns do
    collection do
      get :map
      get :guess
    end
    member do
      get :guess
      post :mark
    end
  end

  resources :visits, :only => :show

  root :to => 'towns#map'

  get "/info" => "public#info", :as => :info

  get "/oauth/connect" => 'instagram#connect', :as => :connect
  get "/oauth/callback" => 'instagram#callback'
  get "/oauth/logout" => 'instagram#logout', :as => :logout

  get "/fetch" => 'instagram#fetch', :as => :fetch
  get "/resolve" => 'instagram#resolve', :as => :resolve
  post "/resolve" => 'instagram#resolve', :as => :resolve

end

app/models/town.rb
# -*- encoding : utf-8 -*-
class Town < ActiveRecord::Base

  attr_accessible :department, :wikiref, :latitude, :longitude, :image_url, :name

  has_many :visits

  scope :visited_by, lambda{|username| joins(:visits).where('visits.username = ?', username).group('towns.id')}
  scope :fully_visited_by, lambda{|username| joins(:visits).where('visits.media_id IS NOT NULL AND visits.username = ?', username).group('towns.id')}
  scope :in, lambda{|department| where(:department => department)}

  def image_url
    
  end

  def self.random
    order("RAND()")
  end
      
  def self.departments
    group(:department).all.map(&:department).compact.sort
  end

  def self.locate(latitude, longitude)
    min = nil
    fit = nil
    all.each do |t|
      diff = (t.latitude - latitude).abs + (t.longitude - longitude).abs
      if !min or diff < min
        min = diff
        fit = t
      end
    end
    fit
  end

end

app/controllers/towns_controller.rb
# -*- encoding : utf-8 -*-
class TownsController < ApplicationController
  
  def index
  end
  
  def map
    render :layout => 'map'
  end
  
  def guess
    
    @x_guess = session[:x_guess] ||= []
    @x_good  = session[:x_good] ||= []
    
    random_visit = Visit.with_image
    random_visit = random_visit.where('town_id NOT IN (?)', @x_good) unless @x_good.empty?
    random_visit = random_visit.random.first
    
    if params[:id]
      @visit = (!params[:id] or params[:id].to_i == 0) ? nil : Visit.find(params[:id])
      @town = @visit.town if @visit
      
      if params[:guess_id]
        @guess_town = Town.find(params[:guess_id])
        @visit = random_visit
        unless @x_good.include? @town.id 
          @x_guess << @town.id
          @x_good << @town.id if @guess_town.id == @town.id
        end
        session[:x_guess] = @x_guess
        session[:x_good]  = @x_good 
      end
    else
      redirect_to :action => :guess, :id => (random_visit ? random_visit.id : 0)
    end
  end
  
  def mark
    if instagram_user
      @town = Town.find(params[:id])
      unless @town.visits.by(instagram_user.username).where('media_id IS NULL').any?
        @town.visits.create({
          :username => instagram_user.username,
          :media_id => nil,
        })
      end
    else 
      render :nothing => true  
    end
  end
  
end

app/helpers/towns_helper.rb
# -*- encoding : utf-8 -*-
module TownsHelper
end

app/views/towns/_box.html.haml
Navštíveno #{Town.fully_visited_by(instagram_user.username).size.size}
(#{Town.visited_by(instagram_user.username).size.size})
z #{Town.count} měst

app/views/towns/_towns_js.html.erb
<script>
  $(function(){

    var mapOptions = {
      center: new google.maps.LatLng(49.75, 14.80),
      zoom: 8,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map"),
        mapOptions);

    var open_info_window = null;

    <% Town.all.each do |town| %>
      <%
        visits = username ? town.visits.by(username).where('media_id IS NOT NULL') : []
        other_visits = username ? town.visits.by(username).where('media_id IS NULL') : []
      %>
      window.marker<%=town.id%> = new google.maps.Marker({
          position: new google.maps.LatLng(<%=town.latitude%>,<%=town.longitude%>),
          map: map,
          <% if (instagram_user && visits.any?)  %>
          icon: '<%= asset_path 'markers/blue_MarkerX.png'%>',
          <% elsif (instagram_user && other_visits.any?) %>
          icon: '<%= asset_path 'markers/paleblue_MarkerX.png'%>',
          <% else %>
          icon: '<%= asset_path 'markers/red_MarkerX.png'%>',
          <% end %>
          title:"<%= town.name %>"
      });

      contentString =
        '<div class="town_info_window">'
        + '<span class="title"><%= town.name %></span>'
        <% unless town.wikiref.blank? %>
        + ' <%= link_to "(wiki)", town.wikiref %>'
        <% end %>
        + '<br />okres <%= town.department %><br />'
        <% visits.each do |visit| %>
        + '<br /> <%= visit.timestamp.strftime("%d. %m. %Y") %><br /><%= link_to_function image_tag(visit.thumbnail_url, :size => '150x150'), "Shadowbox.open({player:\\'img\\',content:\\'#{visit.image_url}\\',height: 612,width:612 });"%>'
        <% end %>
        <% if visits.empty? && other_visits.empty? && instagram_user %>
        + '<br /><%= link_to "označit jako kdysi navštívené", mark_town_path(town), :remote => true, :method => :post %>'
        <% end %>
        + '</div>';

      window.infowindow<%=town.id%> = new google.maps.InfoWindow({
          content: contentString
      });

      google.maps.event.addListener(window.marker<%=town.id%>, 'click', function() {
        if (open_info_window) { open_info_window.close(); }
        if (open_info_window == window.infowindow<%=town.id%>) {
          open_info_window = null;
        } else {
          window.infowindow<%=town.id%>.open(map,marker<%=town.id%>);
          open_info_window = window.infowindow<%=town.id%>;
        }
      });
    <% end %>
  });
</script>

app/views/towns/guess.html.haml
%h1 Poznávačka

- if @guess_town
  - if @guess_town == @town
    %p.good_guess Správně, #{@guess_town.name}!
  - else
    %p.bad_guess Nebyl to #{@guess_town.name}, ale #{@town.name}!

%p.guess_status
  Celkem pokusů: #{@x_guess.size}
  - if @x_guess.any?
    %br
    Skóre: #{"%d%%" % (100.0 * @x_good.size / @x_guess.size)}
  
- if @visit  
  %p
    %img{:src => @visit.image_url}

  %ul.guess
    - (Town.random.where('id != ?', @visit.town_id).limit(4) + [@visit.town]).shuffle.each do |t|
      %li= link_to t.name, {:id => @visit.id, :guess_id => t.id}

app/views/towns/index.html.haml
%h1 Seznam měst

- for town in Town.all
  %p
    = town.name
    = surround '[', ']' do
      = town.department

app/views/towns/map.html.haml
- if instagram_user
  %div#box= render :partial => 'box'

%div#box_menu
  %ul
    %li(style="font-weight:bold")= link_to "URBORETUM", info_path, :style => "color:#f00"
    - if instagram_user
      %li= instagram_user.username
      %li= link_to 'načíst', fetch_path
      %li= link_to 'odhlásit', logout_path
    - else
      %li= link_to "přihlásit", connect_path

= render :partial => 'towns_js', :locals => {:username => instagram_user && instagram_user.username}

app/views/towns/map.iphone.erb
<% self.formats = [:mobile, :html] %>

<div id="box">
  <ul>
    <li style="font-weight:bold"><span style="color:#f00">URBORETUM</span></li>
    <% if !instagram_user %>
      <li><%= link_to "přihlásit", connect_path %></li>
    <% else %>
      <li> Navštíveno <%= Town.fully_visited_by(instagram_user.username).size.size%> (<%= Town.visited_by(instagram_user.username).size.size%>) / <%= Town.count%> </li>
    <% end %>
  </ul>

  <% if instagram_user %>
  <br />
    <ul>
    <li><%= instagram_user.username %></li>
    <li><%= link_to 'načíst', fetch_path %></li>
    <li><%= link_to 'odhlásit', logout_path %></li>
    </ul>
  <% else %>
  <% end %>
</div>

<%= render :partial => 'towns_js', :locals => {:username => instagram_user && instagram_user.username} %>

app/views/towns/mark.js.erb
window.infowindow<%=@town.id%>.close();
window.marker<%=@town.id%>.setIcon('assets/markers/paleblue_MarkerX.png');
// rebuild the info window
//TODO
// update the totals
//TODO